### ISSUE TITLE
May I pass APP_HOME as arguments?

### ISSUE THREAD

**Issue by nobe0716** [line/centraldogma#258]
Hello, 

I recently consider centraldogma as alternative for zookeeper.
And I meet a problem to apply it on my server.

Since centraldogma uses **APP_HOME** as its env variables,
It made a conflict with my pre-exist env variables.

> I have used "~/apps" as **APP_HOME** already,
> so centraldogma misread env and could not start correctly with JSVC errors.

I wish for centraldogma to have more concrete name of env variable such as **CD_APP_HOME**
or to support arguments for **APP_HOME**

Thanks

**Comment by minwoox** [comment]
Hello! @nobe0716 Thank you for your interest about our project.
We are going to figure out the better way to handle this situation, but could you just unset **APP_HOME** or set as empty string before you start the server?

**Comment by nobe0716** [comment]
@minwoox I had already done, and set up CD, but it can occur conflict with pre-exist applications

thanks you for your suggestion.

**Comment by minwoox** [comment]
@nobe0716 Glad to hear that you set up CD!  Please let us know if there is any problem while you are using it.
