### ISSUE TITLE
Repository name 'new' does not work in web UI

### ISSUE THREAD

**Issue by occho** [line/centraldogma#270]
When there's a repository named 'new', the link for the repository view is `/#/{project}/new`.
But, we cannot open the view because the link makes us jump to the view of creating a new repository.

**Comment by hyangtack** [comment]
Thank you for reporting this issue. 🙇 Looks like we need to enhance checking reserved words when creating a new project or repository.

Are you interested in sending a PR for fixing this? 😃

**Comment by occho** [comment]
> Are you interested in sending a PR for fixing this? 😃

Thank you for your suggestion!
But, I think I cannot work on this any time soon, so someone can take it. 🙇

**Comment by hyangtack** [comment]
@occho Ok, no problem. 😃 Thank you again!
