### ISSUE TITLE
'Returning an internal server error: failed to get the value of a parameter: SAMLResponse'

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#379]
We sometimes get the following warning log:

```
[id: 0x1172fb1d, L:... - R:...][h2://.../saml/acs/post#GET] Returning an 
internal server error: failed to get the value of a parameter: SAMLResponse
om.linecorp.armeria.server.saml.SamlException: failed to get the value of a 
parameter: SAMLResponse
```

Should we respond with other status code, such as `400 Bad Request`?

**Comment by hyangtack** [comment]
Need to make Armeria SAML module raise an `IllegalArgumentException` instead of `SamlException` when it failed to find the parameter `SAMLResponse`.
