### ISSUE TITLE
HTTP API - a watch request with a revision number represented as a valid etag must be accepted.

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#415]
When an HTTP API client sends a watch request, it will send an `If-None-Match` header, e.g.

```
If-None-Match: 3
Prefer: wait=60
```

However, `If-None-Match` must have a valid etag rather than just an integer. It has to be `"3"` or `W/"3"`.

To fix this issue, `WatchRequestConverter` must be updated to handle all three formats:

- `<revision>` (for backward compatibility)
- `"<revision>"`
- `W/"<revision>"`

**Comment by TheWeaVer** [comment]
Let me try it. 🙂

**Comment by minwoox** [comment]
Excellent! 😄
