### ISSUE TITLE
Add an option that appends a certain label next to web page title

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#43]
Currently, there's no easy way to know if the CD instance he or she is accessing belongs to BETA or RELEASE zone. We currently show the host name of the instance, but it's not clear enough. We could add a simple text value option whose value is appended to the web page title. e.g. 'Central Dogma (BETA, {hostname})'

**Comment by hyangtack** [comment]
It also would be better to show the current version of the CD instance on the web page. 😃
