### ISSUE TITLE
Create a local repository automatically when mirroring

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#464]
When mirroring from Git to Central Dogma, Central Dogma does not mirror when the target local repository does not exist. Instead, it could create an empty repository when it does not exist. /cc @huydx

**Comment by minwoox** [comment]
@yyuunn0044 You might be also interested in this PR. 😉

**Comment by ikhoon** [comment]
This issue would not need to be addressed since the mirror UI forces users to select a repository from the existing ones.
