### ISSUE TITLE
UI for editing mirror settings

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#50]
Creating and editing mirror settings require manual JSON editing which is time-consuming and error-prone. We should provide a dedicated UI for a meta repository so that a user cannot make a mistake when configuring a mirror.

Also, for some reason, when a bad mirror setting leaked into a meta repository, the UI should provide an easy way to figure out what's wrong with his/her setting.

**Comment by ikhoon** [comment]
Closed by #838
