### ISSUE TITLE
Limits and quotas on API requests

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#528]
Central Dogma server will get huge GC pressure or poor performance if a client outrageously writes commits.
It would be good to detect, alert. and limit a heavy client or repository that over the user-defined quotas.

To achieve this, we need the following features.
- Quotas:  A administrative UI being managed by admin is required.
- Alarm: If a API is over-used, a warn message should be notified to the repository’s administrator. 
- Rate limiting: Central Dogma would use armeria-bucket4j to control API usages.

**Comment by ikhoon** [comment]
I was thinking about how to apportion quota(available resources) across to Central Dogma cluster nodes.
 
* Assumption
	* Central Dogma is a distributed system. It doesn’t fit to use centralized storage such as Redis for sharing and synchronizing the current remaining quota.
	* Traffics will not always be evenly distributed among clusters. In order to maximize the availability of resources, We need to give more quota to the busy server for the remaining resources.
* Algorithms
	* Initially, all clusters have the same capacity evenly divided.
	* The capacity has a specific expiration time. The cluster should renew the lease according to the following logic:
	* Idle node - with less than 80% of utilization for the lease capacity
		* Returns 90% of the remaining capacity, the extra 10% is kept for a buffer 
			* Current capacity: 100 QPS
			* Actual traffic: 60 QPS
			* Unused capacity: 40 QPS
			* Returned capacity: 40 * 0.9 = 36 QPS
	*  Busy node with  more than 90% of utilization
		* If the incoming request exceeds the given capacity, returns  429 Too Many Requests.
			* Clients shall retry with a backoff.
		* When the lease expires, the node tries to acquire more capacity based on the requests so far 
			* If the resource pool has a returned capacity from the idle nodes, busy nodes will take it.
	* Normal nodes with 80~90% utilization  for the lease capacity
		* Renew only the lease.

**Comment by ikhoon** [comment]
Had chat with @minwoox and we decided to implement a prototype using [ZooKeeper quota](https://zookeeper.apache.org/doc/current/zookeeperQuotas.html) and [auto expiration with TTL](https://zookeeper.apache.org/doc/r3.5.3-beta/api/org/apache/zookeeper/ZooKeeper.html#create(java.lang.String,%20byte[],%20java.util.List,%20org.apache.zookeeper.CreateMode,%20org.apache.zookeeper.data.Stat,%20long)).

For example, if a repository has 5 commits/sec quota.
- Set 5 to `/quota/fooProject/barReposotory` 
- Create a node with TTL 1 sec to `/quota/fooProject/barReposotory/`
- If nodes under `/quota/fooProject/barReposotory/` are created more than 5, the newly created node will be rejected by ZooKeeper.

**Comment by gurshafriri** [comment]
👋 @ikhoon do you see this as a potential DoS security issue, or more a "best-practice" improvement? 
If this is a security issue, we (at [snyk](http://snyk.io)) would like to add it to our vulnerability-DB

**Comment by ikhoon** [comment]
Hi @gurshafriri 
I don't think this is a DoS security issue. Central Dogma is a read-centric application. The write performance of Central Dogma highly depends on the number of ZooKeeper clusters. The write throughput will be decreased if the number of ZooKeeper clusters is increased.

I want to add an optional feature that an administrator set a quota to a repository so that users orchestrate Central Dogma more safely.

**Comment by ikhoon** [comment]
Ah... oops... I thought this was made by gurshafriri 😅
