### ISSUE TITLE
FileWatcher should throw NoSuchFileException?

### ISSUE THREAD

**Issue by minwoox** [line/centraldogma#532]
Currently, `FileWatcher.awaitInitialValue(...);` throws `TimeoutException` rather than `NoSuchFileException` if the file, which the watcher tries to watch, does not exist.
It makes the user hard to find the cause.

**Comment by trustin** [comment]
I think there should be an option for this behavior, because some users might want to wait until the file is created. I agree that the default behavior should be to throw an exception.

**Comment by din-seo** [comment]
I try to handle this issue.

**Comment by minwoox** [comment]
Closed via #653
