### ISSUE TITLE
Autoconfigured client creates an armeria client factory bean that can interfere with the user's spring context

### ISSUE THREAD

**Issue by m50d** [line/centraldogma#577]
Example: https://github.com/m50d/centraldogma/commit/fc2f5703a4c64fd99e7a074a1ed19e78c5881cbf - this test fails, but I think it should pass. `dogmaClientFactory` is an internal implementation detail of the CentralDogma client, it shouldn't interfere with the user's existing use of Armeria.

I can't immediately see how to fix this though - setting `autowireCandidate=false` breaks the way `dogmaClientFactory` is currently used. And of course any change to this would be potentially breaking from a user's point of view.

**Comment by minwoox** [comment]
Thanks for the report. I guess introducing a new interface for the Central dogma client factory is the way that we can resolve the issue.
By the way, isn't it solved by adding `@Primary` to the `ClientFactory` you want to use? 🤔

**Comment by ikhoon** [comment]
`@Primary` could be a workaround at the moment.

> I guess introducing a new interface for the Central dogma client factory is the way that we can resolve the issue.

+1 It should be nice to introduce `CentralDogmaClientFactoryConfigurator` and deprecate `@ForCentralDogma`.

**Comment by m50d** [comment]
Exactly, `@Primary` is a workaround for now but I don't think it should be necessary. (In reality my problem was the opposite - someone had configured a service that needed an armeria client factory without providing one, and so the instance from this autoconfiguration was picked up - so as soon as I explicitly configured a `CentralDogma` in the context, that unrelated bean broke).

**Comment by minwoox** [comment]
Yeah, that could be a problem. We need a new interface. 😄 
Are you going to send the PR? or we can handle it.

**Comment by m50d** [comment]
While I'd be very happy to do an implementation, I didn't quite understand the proposed `CentralDogmaClientFactoryConfigurator` approach, so I think it's better to handle on your side if you have an architecture in mind.

**Comment by minwoox** [comment]
No problem at all. 😉 
Let us handle it. Thanks for the report!
