### ISSUE TITLE
0.49.1 download link is missing

### ISSUE THREAD

**Issue by darklore** [line/centraldogma#596]
Cannot download centraldogma binary from installation page.
https://line.github.io/centraldogma/setup-installation.html
It seems 0.49.1 doesn't include tgz asset.
https://github.com/line/centraldogma/releases/tag/centraldogma-0.49.1

**Comment by ikhoon** [comment]
Sorry, I missed attaching tarball to the release note.
You can now download Central Dogma 0.49.1.
