### ISSUE TITLE
Disallow to create non-reserved files in meta repository

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#633]
A meta repository is a special repository to manage a project.
So it has restricted permission. 
However, some users use a meta repository as a normal repository that we do not expect.
It would be nice to prohibit users from creating personal files.

**Comment by ghkim3221** [comment]
Let me fix this issue

**Comment by ghkim3221** [comment]
Additionally, how about hiding the `meta` directory from the web UI so that users can know naturally the `meta` directory is for internal usage. We already have `Go to metadata` button.

**Comment by minwoox** [comment]
> Additionally, how about hiding the meta directory from the web UI so that users can know naturally the meta directory is for internal usage. We already have Go to metadata button.

That's brilliant! 😆

**Comment by ikhoon** [comment]
To hide `meta` folder, we need to provide a GUI for the Git mirror service.

**Comment by minwoox** [comment]
I thought you are talking to hide the `meta` repository from a normal user and allow admins to see that.
We cannot hide it completely as @ikhoon said because there's no way to set the mirroring without seeing it.
https://github.com/line/centraldogma/issues/50
This is a related issue. 😉

**Comment by ikhoon** [comment]
Thanks, @ghkim3221 in advance. 🎨

**Comment by minwoox** [comment]
> Additionally, how about hiding the meta directory from the web UI so that users can know naturally the meta directory is for internal usage. We already have Go to metadata button.

I think we can hide `dogma` repository because it only contains `metadata.json` and we can see the content from the metadata UI. 😉
