### ISSUE TITLE
Switch from Angular.js to Vue.js

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#66]
Angular.js is showing its age and thus we should migrate to something with brighter future. During the migration, we also may want to migrate from Bootstrap to Material design

**Comment by djKooks** [comment]
@trustin Seems good! How is the plan for this?

**Comment by trustin** [comment]
We are currently talking to our front-end engineers to see if they are interested. Will post the update here. You might want to look into other issues meanwhile. :-)

**Comment by djKooks** [comment]
@trustin Thanks. Because I'm also AngularJS engineer and faced some issues that are not being managed, it seems good plan to migrate.

**Comment by ikhoon** [comment]
This issue is no longer valid. We are migrating Angualar.js into React.
