### ISSUE TITLE
Feature request: Copy api url

### ISSUE THREAD

**Issue by jay0129** [line/centraldogma#665]
I wanted to find API url because I want to use `curl` to collect my configuration.

I finally found the api url, and it looks like this:
`curl http://xx.xx.xx.xx:xxxxx/api/v1/projects/food/repos/dogma/contents/apple`
where `food` is a project name, `dogma` is a user repository name and `apple` is a content name.

I found it by using the command line tool 'dogma' since it returned:
```
[
  {
    "type": "TEXT",
    "path": "/apple",
    "revision": 4,
    "url": "/api/v1/projects/food/repos/dogma/contents/apple"
  }
]
```

However, it would be better if I can get this url easily from the web console.

**Comment by ikhoon** [comment]
Fixed by #776
