### ISSUE TITLE
Display localized timestamp

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#688]
Central Dogma shows the creation time of commits with UTC. It found it difficult to convert the UTC time to a local time without external tools.
It would be useful to display a localized timestamp in the history view of the web console.

**Comment by rainy789** [comment]
It looks like this has been addressed. 

<img width="938" alt="Screen Shot 2023-02-21 at 22 54 50" src="https://user-images.githubusercontent.com/5079588/220394721-c3d4393b-7578-4a69-ae2c-5f1bccce26fc.png">

**Comment by ikhoon** [comment]
Indeed! 🫡
