### ISSUE TITLE
How to update from the central dogma client when git-to-cd mirror is enable?

### ISSUE THREAD

**Issue by andochiwa** [line/centraldogma#694]
When I enable git-to-cd mirror, the changes from the client will be overwritten.
Is there a way to enable mirror and still allow client updates?

And..is there any way to disable the central dogma from modifying files after enabling mirror? (besides permission control)

**Comment by ikhoon** [comment]
Did you mean git-to-cd mirror? cd-to-git mirror hasn't been implemented yet. https://github.com/line/centraldogma/issues/53

>  Is there a way to enable mirror and still allow client updates?

Central Dogma repositories allow a single branch so it is not supported to merge to two branches. 

> And..is there any way to disable the central dogma from modifying files after enabling mirror?

If I understand correctly, the question meant you wanted to prohibit files from modifying by Central Dogma APIs when mirroring is enabled?

**Comment by andochiwa** [comment]
```
Did you mean git-to-cd mirror? cd-to-git mirror hasn't been implemented yet
```
Yes, I wrote it wrong
```
If I understand correctly, the question meant you wanted to prohibit files from modifying by Central Dogma APIs when mirroring is enabled?
```
I want to prohibit files from Central-dogma-UI when mirroring is enabled, as this can be confusing when collaborating with multiple people.

And there are servers using central-dogma client for push file and i want to know if there is a way keep it working.

**Comment by andochiwa** [comment]
I solved it by disable client push, closing
