### ISSUE TITLE
The equals implementation in AbstractCommand is not correct

### ISSUE THREAD

**Issue by amaembo** [line/centraldogma#751]
Here:
https://github.com/line/centraldogma/blob/c59d2a1defdb7eda3a27959eca0630fd261034cd/server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommand.java#L62

It says:
```java
        if (!(this instanceof AbstractCommand)) {
            return false;
        }
```

This condition is always false, as `this` is always `AbstractCommand`. It should be instead:
```java
        if (!(obj instanceof AbstractCommand)) {
            return false;
        }
```

It's interesting that IntelliJ IDEA tried to warn about this, but the warning was suppressed with `@SuppressWarnings("EqualsWhichDoesntCheckParameterClass")`. After the fix, the suppression would be unnecessary.

**Comment by ikhoon** [comment]
It sounds like a bug. Are you interested in sending a PR?

**Comment by amaembo** [comment]
Sure, see #752.

**Comment by ikhoon** [comment]
Thanks! By the way, how did you find the bug? Are you using Central Dogma?

**Comment by amaembo** [comment]
@ikhoon no, I'm doing some research about static analysis and program mistakes for my book. I may mention this case in the book if you don't mind :-)

**Comment by ikhoon** [comment]
> I may mention this case in the book if you don't mind :-)

Absolutely. I'm looking forward to your book! I'd like to read it when it is published. ❤️
