### ISSUE TITLE
Replication configuration additionalProperties

### ISSUE THREAD

**Issue by 2017029570** [line/centraldogma#753]
Hello,

I've been trying to composing my conf/dogma.json for replication following the wiki
(https://line.github.io/centraldogma/setup-configuration.html)

I would like to use `clientPortAddress` property of zookeeper in additionalProperties field,
but the field isn't added in `/opt/centraldogma/data/_zookeepr/config.properties`
ex) `"additionalProperties": { "clientPortAddress":"123.123.123.123" },`

Is there any solution to use `clientPortAddress` property to zookeeper config?

***
EDIT

Additionally, I attached the legal server format.
https://zookeeper.apache.org/doc/r3.5.3-beta/zookeeperReconfig.html#ch_reconfig_format
> Starting with 3.5.0 the clientPort and clientPortAddress configuration parameters should no longer be used. Instead, this information is now part of the server keyword specification, which becomes as follows:
server.\<positive id> = \<address1>:\<port1>:\<port2>[:role];[\<client port address>:]\<client port>

The zookeeper config file format which is made by dogma doesn't look like the legal format.

**Comment by minwoox** [comment]
Hi, we use ZooKeeper as a replication queue and for locking so clients cannot directly connect to ZooKeeper.
Instead, a client connects via the Central Dogma server port and sends a request. The port is specified in the `ports` property:
```
{
  "dataDir": "./data",
  "ports": [
    {
      "localAddress": {
        "host": "*",
        "port": 36462
      },
      "protocols": [
        "http"
      ]
    }
  ],
  ...
}
```

**Comment by 2017029570** [comment]
Thank you for your reply!

I'd like to use a zookeeper's `quorumListenOnAllIPs` option, Is it also impossible ?

**Comment by minwoox** [comment]
> I'd like to use a zookeeper's quorumListenOnAllIPs option, Is it also impossible ?

Could you tell me more in detail? What do you need it for and what are you going to use it for?

**Comment by 2017029570** [comment]
I'm struggling to compose dogma replication with docker container and I guessed the issue is from zookeeper .
So, I'd like to test following the comment below.
  - https://issues.apache.org/jira/browse/ZOOKEEPER-2164?focusedCommentId=17036846&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17036846

**Comment by minwoox** [comment]
Could you share your configuration via DM? I think we can talk in our Slack. 😉

**Comment by 2017029570** [comment]
I'll send you a slack message soon :)

**Comment by trustin** [comment]
I guess we can whitelist `quorumListenOnAllIPs` nevertheless.

**Comment by minwoox** [comment]
This is where we whitelist the property:
https://github.com/line/centraldogma/blob/297cfd056439ce88fe1f46f2b1d83a3c15ec65f3/server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java#L432-L438

**Comment by minwoox** [comment]
I have actually implemented it. 
https://github.com/minwoox/centraldogma/commit/ca358cfcb1df68029d924b404cec94ea0d32b77d#diff-68f354aba3167db1c3da6f6a6af6423e6957013d80ac4bc1922bcb70d0210435R439

Let me send a PR. 😉
