### ISSUE TITLE
Add Apple Silicon binary for CLI

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#779]
Currently, we only support amd64 for macOS CLI.
Go binaries are hosted in the release notes at https://github.com/line/centraldogma-go/releases/tag/0.0.1
We may build go CLI binaries for Apple Silicon and release it as 0.0.2

**Comment by Dogacel** [comment]
I am not sure if it is worth the effort but how about modifying the github actions workflow [here](https://github.com/line/centraldogma-go/blob/0.0.1/.github/workflows/actions_build.yml#L18) to include github hosted m1 runners and publish the binaries as a part of the release workflow 😅

**Comment by ikhoon** [comment]
It is a good idea. centraldogma-go isn't actively developed since the API of Central Dogma is stable. That said, it would be worth automatically releasing the binaries with GitHub Actions.

**Comment by Dogacel** [comment]
> It is a good idea. centraldogma-go isn't actively developed since the API of Central Dogma is stable. That said, it would be worth automatically releasing the binaries with GitHub Actions.

If it is not actively developed, can I build it in my local and upload to at least provide a quick solution? Later a new issue can be opened regarding automated release pipeline?

**Comment by ikhoon** [comment]
I added a script that generates binaries for well-known architectures and operating systems.
https://github.com/line/centraldogma-go/pull/60
As you said, we will automate the release pipeline if it is frequently updated.
Thanks for your interest and idea. 😃

**Comment by Dogacel** [comment]
> I added a script that generates binaries for well-known architectures and operating systems. [line/centraldogma-go#60](https://github.com/line/centraldogma-go/pull/60) As you said, we will automate the release pipeline if it is frequently updated. Thanks for your interest and idea. 😃

I did not know it was possible to compile for a specific architecture like that. I thought it was like iOS apps that need to be compiled on a Mac device 😆

Script looks good.
