### ISSUE TITLE
Fetch only the recent commits when cloning a remote Git repository for mirroring

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#801]
Currently, Central Dogma clones the entire repository when mirroring a remote Git repository. We don't need to fetch the entire graph but only the latest tree. We could specify `--depth` option so we don't fetch the Git objects that are not used actually.

Related API:
- `FetchCommand.setDepth(int)`
  - https://download.eclipse.org/jgit/site/6.4.0.202211300538-r/apidocs/org/eclipse/jgit/api/FetchCommand.html#setDepth(int)

Also, we should:

- ensure old commits are also pruned when the remote Git repo adds a new commit or force-pushes; and
- write a test

**Comment by trustin** [comment]
Closed via https://github.com/line/centraldogma/pull/808 Thanks a lot, @thachlp! 🙇

**Comment by thachlp** [comment]
Thank you for your support @trustin
