### ISSUE TITLE
Should we add tool for scan vulnerabilities like Snyk?

### ISSUE THREAD

**Issue by thachlp** [line/centraldogma#815]
Should we add a tool for automatically scanning vulnerabilities in code, open-source dependencies, ... like Snyk?
Here is an example of vulnerabilities on `server-auth/webapp/package.json`
![image](https://user-images.githubusercontent.com/11583408/222355856-a3264de3-2d0f-41ef-856b-286c12e35ebe.png)

**Comment by trustin** [comment]
GitHub Dependabot already sends periodic e-mail about the vulnerable dependencies to devs. What's the advantage of having Snyk in addition to Dependabot e-mail reports? If it is useful enough, we'd be happy to use it. 😄

**Comment by thachlp** [comment]
> 
Don't know we have Dependabot, I think we don't need to use Snyk.
I close this issue.
