### ISSUE TITLE
Support ed25519 SSH key pairs by switching from JSch to Apache MINA SSHd

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#817]
Since JGit 5.2, JGit provides an alternative SSH transport implementation based on Apache MINA SSHd, which supports `ed25519` which is currently not supported by JSch.

We should make a switch given JSch didn't get any updates since 2018 and `ed25519` is now the recommended SSH key pair type.

**Comment by thachlp** [comment]
I am working on this
