### ISSUE TITLE
 How can I migrate centraldogma service smoothly

### ISSUE THREAD

**Issue by ChenJiahui0** [line/centraldogma#840]
I wish there was a specific how-to guide.

My current service version is 0.31.0, using zookeeper as the replication mechanism. I now need to collectively migrate the Centraldogma service to another cluster, what should I do.

**Comment by ikhoon** [comment]
The whole important information for Central Dogma repositories and metadata are stored in the `data` folder. If you simply copy the snapshot to the new cluster, all data will be restored in the new server set.


1. To safely back up the data, we have to update the server's status to stop the replication mode and enter the read-only mode via REST API. Note that an administrative token should be used to update the server's status.
```sh
$ curl -X PATCH \
    -H 'Authorization: bearer appToken-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' \
    -H 'Content-Type: application/json-patch+json' \
    -d '[{ "op": "replace", "path": "/writable", "value": false },
         { "op": "replace", "path": "/replicating", "value": false }]' \
    -w "\nStatus: %{http_code}\n" \
    http://host:36462/api/v1/status
```
https://github.com/line/centraldogma/blob/d596a340e68598afd981cfd8e3d18f34761f5eb9/server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java#L63-L69

2. Double-check if replication is stopped:
```sh
$ curl \
    -H 'Authorization: bearer appToken-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' \
    http://host:36462/api/v1/status
```

3. Once the cluster enters the read-only mode, create a snapshot of the `data` folder and copy it to the new cluster. `_mirrors` and `_zookeeper` could be excluded from the snapshot.
