### ISSUE TITLE
Docs graph seems to be broken

### ISSUE THREAD

**Issue by MichalMichalak** [line/centraldogma#847]
Hello. It seems there's graph missing on the docs page: https://line.github.io/centraldogma/concepts.html

I'm just guessing, judging by the image which displays the message:

> Dot Executable: /opt/local/bin/dot
> File does not exist
> Cannot find Graphviz
> ...

**Comment by jrhee17** [comment]
Oops 😅    Thanks for letting us know

**Comment by ikhoon** [comment]
Fixed by #848
