### ISSUE TITLE
Update Github Workflow CI build target

### ISSUE THREAD

**Issue by thachlp** [line/centraldogma#911]
From the [build requirement](https://github.com/line/centraldogma/blob/5166201498e5c23fadaf579262cfe8bbb82dd8d6/CONTRIBUTING.md), we should use JDK13 or later, so should we remove Java 8 and Java 11 on target build?

And Since Java 21 is LTS and released on September 19, 2023, should we add Java 21 to CI build target?

**Comment by ikhoon** [comment]
The build requirement is only used for the build source code. Java 8 is set via `-release 8` compiler option.

> so should we remove Java 8 and Java 11 on target build?

Central Dogma client may support Java 8 for a long time because many services in LINE still actively use Java 8 for production.
