### ISSUE TITLE
csrfTokenRequiredForThrift field missing from documentation

### ISSUE THREAD

**Issue by thachlp** [line/centraldogma#925]
The `conf/dogma.json` include `csrfTokenRequiredForThrift` but this field missing on the documentation site: https://line.github.io/centraldogma/setup-configuration.html
I think it is better to add/describe it if it is deprecated.

**Comment by minwoox** [comment]
We are going to remove Thrift support so let's just delete the property from the `dogma.json`. 😉

**Comment by thachlp** [comment]
Yes, I updated my pr https://github.com/line/centraldogma/pull/923
