### ISSUE TITLE
Remote branch show null when unspecified 

### ISSUE THREAD

**Issue by thachlp** [line/centraldogma#933]
When unspecified a branch name, the message show `#null`. Should we improve it?
![image](https://github.com/line/centraldogma/assets/11583408/2f164675-d8fc-41a5-b696-3190a90c4b2c)

**Comment by thachlp** [comment]
In my opinion, I think we should omit `#null` when using the default branch. How do you think?

**Comment by minwoox** [comment]
Yup, let's do that. 👍

**Comment by thachlp** [comment]
There is too long with no update, so I closed it
