### ISSUE TITLE
Provide a BOM of all Central Dogma artifacts

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#95]
Related: https://github.com/line/armeria/issues/852

Provide BOM for Central Dogma artifacts to manage dependencies at downstreams.

Here is sample BOM that a project provides:
* http://platform.spring.io/platform/ , `io.spring.platform:platform-bom:Brussels-SR5`
* https://repo1.maven.org/maven2/io/spring/platform/platform-bom/Brussels-SR5/

**Comment by trustin** [comment]
Perhaps we could give [Nebular](https://nebula-plugins.github.io/) plugins a try.

**Comment by imasahiro** [comment]
Now centraldogma provides bom, right?
https://search.maven.org/#artifactdetails%7Ccom.linecorp.centraldogma%7Ccentraldogma-bom%7C0.24.0%7Cpom

**Comment by trustin** [comment]
You are correct. Let me close this issue. Thanks!
