### ISSUE TITLE
Remove ".git" suffix when creating a repository

### ISSUE THREAD

**Issue by minwoox** [line/centraldogma#956]
To simplify the operation that uses the repository name such as the authorization system.
GitHub also removes the suffix automatically when creating a repository.
<img width="730" alt="image" src="https://github.com/line/centraldogma/assets/25103250/4c574b11-d665-4af9-ba97-ea3487711f4d">

**Comment by ikhoon** [comment]
I slightly prefer rejecting a repo name ending with `.git` instead of an automatic strip.

**Comment by minwoox** [comment]
Alright, it's time to vote. @line/dx 

For the record, GitHub just removes the suffix.
<img width="812" alt="image" src="https://github.com/line/centraldogma/assets/25103250/13c8b488-7c02-4f53-9b6b-381a67423250">

**Comment by minwoox** [comment]
On second thought, I also prefer rejecting it because we might change the underlying database from Git to another.
But please let me know if you have any other opinions.
